# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d16af2792b5318303a78f1b914d42378dc3731ee574b0a498db6d172a5eaa88312c339e43c606357541f60e5b4c0489a91a15c8bb94234a14e4d60c3cbf9eb7

test:
  secret_key_base: ce411bd00e95a9acf281381262cc79a15a896800a520e9a0d64b5707c36b309d093e5b52b9ca5acb1d3334033337fb8f2c459aa5c6141f9aca321b47ae8fe225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
